SamacSys ECAD Model
190947/1946058/2.50/8/2/Relay or Contactor

DESIGNSPARK_INTERMEDIATE_ASCII

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "r200_70"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 0.7) (shapeHeight 2))
		(padShape (layerNumRef 16) (padShapeType Rect)  (shapeWidth 0) (shapeHeight 0))
	)
	(textStyleDef "Default"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 50 mils)
			(strokeWidth 5 mils)
		)
	)
	(patternDef "IM07GR" (originalName "IM07GR")
		(multiLayer
			(pad (padNum 1) (padStyleRef r200_70) (pt -3.8, -3) (rotation 0))
			(pad (padNum 2) (padStyleRef r200_70) (pt -0.6, -3) (rotation 0))
			(pad (padNum 3) (padStyleRef r200_70) (pt 1.6, -3) (rotation 0))
			(pad (padNum 4) (padStyleRef r200_70) (pt 3.8, -3) (rotation 0))
			(pad (padNum 5) (padStyleRef r200_70) (pt 3.8, 3) (rotation 0))
			(pad (padNum 6) (padStyleRef r200_70) (pt 1.6, 3) (rotation 0))
			(pad (padNum 7) (padStyleRef r200_70) (pt -0.6, 3) (rotation 0))
			(pad (padNum 8) (padStyleRef r200_70) (pt -3.8, 3) (rotation 0))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt -0.308, 0.005) (textStyleRef "Default") (isVisible True))
		)
		(layerContents (layerNumRef 28)
			(line (pt -5 3) (pt 5 3) (width 0.2))
		)
		(layerContents (layerNumRef 28)
			(line (pt 5 3) (pt 5 -3) (width 0.2))
		)
		(layerContents (layerNumRef 28)
			(line (pt 5 -3) (pt -5 -3) (width 0.2))
		)
		(layerContents (layerNumRef 28)
			(line (pt -5 -3) (pt -5 3) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt -5 -3) (pt -5 3) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt 5 3) (pt 5 -3) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(arc (pt -3.86, -4.553) (radius 0.03677) (startAngle 0.0) (sweepAngle 0.0) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(arc (pt -3.86, -4.553) (radius 0.03677) (startAngle 180.0) (sweepAngle 180.0) (width 0.2))
		)
	)
	(symbolDef "IM26GR" (originalName "IM26GR")

		(pin (pinNum 1) (pt 0 mils 0 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -25 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 2) (pt 0 mils -100 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -125 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 3) (pt 0 mils -200 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -225 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 4) (pt 0 mils -300 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -325 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 5) (pt 1200 mils -300 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 970 mils -325 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 6) (pt 1200 mils -200 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 970 mils -225 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 7) (pt 1200 mils -100 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 970 mils -125 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 8) (pt 1200 mils 0 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 970 mils -25 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(line (pt 200 mils 100 mils) (pt 1000 mils 100 mils) (width 6 mils))
		(line (pt 1000 mils 100 mils) (pt 1000 mils -400 mils) (width 6 mils))
		(line (pt 1000 mils -400 mils) (pt 200 mils -400 mils) (width 6 mils))
		(line (pt 200 mils -400 mils) (pt 200 mils 100 mils) (width 6 mils))
		(attr "RefDes" "RefDes" (pt 1050 mils 300 mils) (justify Left) (isVisible True) (textStyleRef "Default"))

	)
	(compDef "IM26GR" (originalName "IM26GR") (compHeader (numPins 8) (numParts 1) (refDesPrefix K)
		)
		(compPin "1" (pinName "+") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "2" (pinName "NC_1") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "3" (pinName "COM_1") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "4" (pinName "NO_1") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "5" (pinName "NO_2") (partNum 1) (symPinNum 5) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "6" (pinName "COM_2") (partNum 1) (symPinNum 6) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "7" (pinName "NC_2") (partNum 1) (symPinNum 7) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "8" (pinName "-") (partNum 1) (symPinNum 8) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "IM26GR"))
		(attachedPattern (patternNum 1) (patternName "IM07GR")
			(numPads 8)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
				(padNum 3) (compPinRef "3")
				(padNum 4) (compPinRef "4")
				(padNum 5) (compPinRef "5")
				(padNum 6) (compPinRef "6")
				(padNum 7) (compPinRef "7")
				(padNum 8) (compPinRef "8")
			)
		)
		(attr "Mouser Part Number" "655-IM26GR")
		(attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-Axicom/IM26GR?qs=g%252BEszo6zu8Mzp1wukcNrqQ%3D%3D")
		(attr "Manufacturer_Name" "TE Connectivity")
		(attr "Manufacturer_Part_Number" "IM26GR")
		(attr "Description" "Body Features: Product Weight .75 G | Insulation Special Features 2500V Initial Surge Withstand Voltage between Contacts & Coil | Product Weight .026 OZ | Contact Features: Contact Arrangement 2 Form C (2 CO) | Contact Number of Poles 2 | Contact Current Rating (Max) 2 AMP | Contact Special Features Bifurcated/Twin Contacts | Contact Plating Material Gold | Contact Base Material PdRu+Au | Contact Current Class 0  2 AMP | Dimensions: Product Length .393 INCH | Width Class (Mechanical) 0  6 MM | Product")
		(attr "Datasheet Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=108-98001&DocType=Data%20Sheet&DocLang=English&PartCntxt=3-1462039-1&DocFormat=pdf")
	)

)
