(part "3550100RJT"
    (packageRef "RESC11050X120N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "279-3550100RJT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-Holsworthy/3550100RJT?qs=gZXFycFWdAMoLDipEZ%252BhPg%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "3550100RJT")
    (property "Description" "CGS - TE CONNECTIVITY - 3550100RJT - SMD Chip Resistor, 100 ohm, +/- 5%, 5 W, 4320 [11050 Metric], Thick Film, High Power")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773204-6&DocType=DS&DocLang=English")
    (property "symbolName1" "3550100RJT")
)
