(part "IM26GR"
    (packageRef "IM07GR")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "COM_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NO_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NO_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "COM_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "NC_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "161")
    (property "Mouser_Part_Number" "655-IM26GR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-Axicom/IM26GR?qs=g%252BEszo6zu8Mzp1wukcNrqQ%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "IM26GR")
    (property "Description" "Body Features: Product Weight .75 G | Insulation Special Features 2500V Initial Surge Withstand Voltage between Contacts & Coil | Product Weight .026 OZ | Contact Features: Contact Arrangement 2 Form C (2 CO) | Contact Number of Poles 2 | Contact Current Rating (Max) 2 AMP | Contact Special Features Bifurcated/Twin Contacts | Contact Plating Material Gold | Contact Base Material PdRu+Au | Contact Current Class 0  2 AMP | Dimensions: Product Length .393 INCH | Width Class (Mechanical) 0  6 MM | Product")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=108-98001&DocType=Data%20Sheet&DocLang=English&PartCntxt=3-1462039-1&DocFormat=pdf")
    (property "symbolName1" "IM26GR")
)
