SamacSys ECAD Model
1953943/1946058/2.50/9/4/Connector

DESIGNSPARK_INTERMEDIATE_ASCII

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "c165_h110"
		(holeDiam 1.1)
		(padShape (layerNumRef 1) (padShapeType Ellipse)  (shapeWidth 1.650) (shapeHeight 1.650))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 1.650) (shapeHeight 1.650))
	)
	(padStyleDef "s165_h110"
		(holeDiam 1.1)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 1.650) (shapeHeight 1.650))
		(padShape (layerNumRef 16) (padShapeType Rect)  (shapeWidth 1.650) (shapeHeight 1.650))
	)
	(padStyleDef "c345_h230"
		(holeDiam 2.3)
		(padShape (layerNumRef 1) (padShapeType Ellipse)  (shapeWidth 3.450) (shapeHeight 3.450))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 3.450) (shapeHeight 3.450))
	)
	(textStyleDef "Default"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 50 mils)
			(strokeWidth 5 mils)
		)
	)
	(patternDef "KMDGX8SN" (originalName "KMDGX8SN")
		(multiLayer
			(pad (padNum 1) (padStyleRef s165_h110) (pt 0.000, 0.000) (rotation 90))
			(pad (padNum 2) (padStyleRef c165_h110) (pt -2.600, 0.000) (rotation 90))
			(pad (padNum 3) (padStyleRef c165_h110) (pt 2.100, 0.000) (rotation 90))
			(pad (padNum 4) (padStyleRef c165_h110) (pt 0.000, 2.500) (rotation 90))
			(pad (padNum 5) (padStyleRef c165_h110) (pt -4.700, 0.000) (rotation 90))
			(pad (padNum 6) (padStyleRef c165_h110) (pt 2.100, 2.500) (rotation 90))
			(pad (padNum 7) (padStyleRef c165_h110) (pt -2.200, 2.500) (rotation 90))
			(pad (padNum 8) (padStyleRef c165_h110) (pt -4.700, 2.500) (rotation 90))
			(pad (padNum 9) (padStyleRef c345_h230) (pt -1.300, -3.800) (rotation 90))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt -1.300, -2.250) (textStyleRef "Default") (isVisible True))
		)
		(layerContents (layerNumRef 28)
			(line (pt -8.3 4) (pt 5.7 4) (width 0.2))
		)
		(layerContents (layerNumRef 28)
			(line (pt 5.7 4) (pt 5.7 -8.5) (width 0.2))
		)
		(layerContents (layerNumRef 28)
			(line (pt 5.7 -8.5) (pt -8.3 -8.5) (width 0.2))
		)
		(layerContents (layerNumRef 28)
			(line (pt -8.3 -8.5) (pt -8.3 4) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt -8.3 -8.5) (pt 5.7 -8.5) (width 0.1))
		)
		(layerContents (layerNumRef 18)
			(line (pt 5.7 -8.5) (pt 5.7 4) (width 0.1))
		)
		(layerContents (layerNumRef 18)
			(line (pt 5.7 4) (pt -8.3 4) (width 0.1))
		)
		(layerContents (layerNumRef 18)
			(line (pt -8.3 4) (pt -8.3 -8.5) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt -9.3 -9.5) (pt 6.7 -9.5) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt 6.7 -9.5) (pt 6.7 5) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt 6.7 5) (pt -9.3 5) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt -9.3 5) (pt -9.3 -9.5) (width 0.1))
		)
	)
	(symbolDef "KMDGX-8S-N" (originalName "KMDGX-8S-N")

		(pin (pinNum 1) (pt 0 mils 0 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -25 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 2) (pt 0 mils -100 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -125 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 3) (pt 0 mils -200 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -225 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 4) (pt 0 mils -300 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -325 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 5) (pt 0 mils -400 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -425 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 6) (pt 900 mils 0 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 670 mils -25 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 7) (pt 900 mils -100 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 670 mils -125 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 8) (pt 900 mils -200 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 670 mils -225 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 9) (pt 900 mils -300 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 670 mils -325 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(line (pt 200 mils 100 mils) (pt 700 mils 100 mils) (width 6 mils))
		(line (pt 700 mils 100 mils) (pt 700 mils -500 mils) (width 6 mils))
		(line (pt 700 mils -500 mils) (pt 200 mils -500 mils) (width 6 mils))
		(line (pt 200 mils -500 mils) (pt 200 mils 100 mils) (width 6 mils))
		(attr "RefDes" "RefDes" (pt 750 mils 300 mils) (justify Left) (isVisible True) (textStyleRef "Default"))

	)
	(compDef "KMDGX-8S-N" (originalName "KMDGX-8S-N") (compHeader (numPins 9) (numParts 1) (refDesPrefix J)
		)
		(compPin "1" (pinName "1") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "2" (pinName "2") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "3" (pinName "3") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "4" (pinName "4") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "5" (pinName "5") (partNum 1) (symPinNum 5) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "6" (pinName "6") (partNum 1) (symPinNum 6) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "7" (pinName "7") (partNum 1) (symPinNum 7) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "8" (pinName "8") (partNum 1) (symPinNum 8) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "MH1" (pinName "MH1") (partNum 1) (symPinNum 9) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "KMDGX-8S-N"))
		(attachedPattern (patternNum 1) (patternName "KMDGX8SN")
			(numPads 9)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
				(padNum 3) (compPinRef "3")
				(padNum 4) (compPinRef "4")
				(padNum 5) (compPinRef "5")
				(padNum 6) (compPinRef "6")
				(padNum 7) (compPinRef "7")
				(padNum 8) (compPinRef "8")
				(padNum 9) (compPinRef "MH1")
			)
		)
		(attr "Mouser Part Number" "806-KMDGX-8S-N")
		(attr "Mouser Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=806-KMDGX-8S-N")
		(attr "Manufacturer_Name" "Kycon")
		(attr "Manufacturer_Part_Number" "KMDGX-8S-N")
		(attr "Description" "Circular DIN Connectors 8P R/A NO SHIELD GOLD PLATED")
		(attr "Datasheet Link" "https://componentsearchengine.com/Datasheets/1/KMDGX-8S-N.pdf")
		(attr "Height" "13 mm")
	)

)
