(part "KMDGX-8S-N"
    (packageRef "KMDGX8SN")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "MH1" (symbPinId 9) (portName "MH1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "806-KMDGX-8S-N")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=806-KMDGX-8S-N")
    (property "Manufacturer_Name" "Kycon")
    (property "Manufacturer_Part_Number" "KMDGX-8S-N")
    (property "Description" "Circular DIN Connectors 8P R/A NO SHIELD GOLD PLATED")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/KMDGX-8S-N.pdf")
    (property "symbolName1" "KMDGX-8S-N")
)
