(part "CHSA3920R0003F"
    (packageRef "CHSA3920R0003F")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "504-CHSA3920R0003F")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bussmann-Eaton/CHSA3920R0003F?qs=By6Nw2ByBD3h3Nqv5wmZ%252Bw%3D%3D")
    (property "Manufacturer_Name" "Eaton")
    (property "Manufacturer_Part_Number" "CHSA3920R0003F")
    (property "Description" "Current Sense Resistors - SMD CHS, 3920 SIZE, 10 Watt, 0.3 mohm, AEC-Q")
    (property "Datasheet_Link" "https://www.eaton.com/content/dam/eaton/products/electronic-components/resources/data-sheet/eaton-chsa-automotive-smd-current-sense-resistor-metal-shunt-data-sheet-elx1223-en.pdf")
    (property "symbolName1" "CHSA3920R0003F")
)
